# the language
lang: en
# author info
author:
  name: Days Rocks
  email: daysrocks@gmail.com
  twitter: '@days_rocks_app'
# title and description
title: Days
description: keep your ...
# the url this will be published at
url: https://days.rocks
baseurl: /
# the theme colour
color:
# location of some files
css: src/css/index.css
scripts: src
favicon:
# alternative to JEKYLL_ENV
development: true
# google analytics
analytics:
# put into dist
destination: ./dist/
ignore: node_modules/
